// MODAL CONFIRM
export const SHOW_MODAL_CONFIRM = 'SHOW_MODAL_CONFIRM'
export const HIDE_MODAL_CONFIRM = 'HIDE_MODAL_CONFIRM'

// AUTH
export const UPDATE_AUTH = 'UPDATE_AUTH'
export const CLEAR_AUTH = 'CLEAR_AUTH'

// TOASTS
export const CREATE_TOAST = 'CREATE_TOAST'
export const REMOVE_TOAST = 'REMOVE_TOAST'
